services:
  db_user:
    image: postgres:17.6-alpine3.22
    container_name: user_db_container
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d user_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  db_workout:
    image: postgres:17.6-alpine3.22
    container_name: workout_db_container
    environment:
      POSTGRES_DB: workout_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - workout_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d workout_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  consul:
    image: hashicorp/consul:1.15
    container_name: fitnessmicro-consul-1
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -dev -client=0.0.0.0"

volumes:
  user_postgres_data:
  workout_postgres_data: