spring:
  application:
    name: gateway

  config:
    import: "optional:consul:"

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        port: ${server.port}
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${server.port}

    gateway:
      server:
        webflux:
          routes:
            - id: user
              uri: lb://user
              predicates:
                - Path=/api/user/**

server:
  port: 8100

management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]